version: '2.3'

services:

  nft3-frontend:
    build: ./src/frontend/.
    ports:
      - 6060:6060
    depends_on:
      - nft3-api

  nft3-api:
    build: ./src/api/.
    ports:
      - 6060:6060
    environment:
      DATABASE_URL: postgres://postgres:pass@postgres-docker/nft3_api
    depends_on:
      - postgres

  postgres:
    image: postgres:14.2
    hostname: postgres-docker
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: nft3_api
    volumes:
        - ./db/up.sql:/docker-entrypoint-initdb.d/up.sql